batch_size: 128
epoch: 200 
optimizer:
  motion_lr: 1.0e-05
  text_lr: 1.0e-05
  head_lr: 1.0e-05
train_text_encoder: false
seed: 42

# Logging
log_interval: 100
log_loss_components: true  # Log individual loss components